services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: tamamdir
      POSTGRES_USER: tamamdir
      POSTGRES_PASSWORD: tamamdir
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
